# fly.toml
app = "solar-accounting-frosty-glitter-8991"
primary_region = "bom"

[env]
SPRING_PROFILES_ACTIVE = "prod"

[http_service]
internal_port = 8080
force_https = true
auto_stop_machines = true
auto_start_machines = true
min_machines_running = 0
processes = ["app"]

# If you don't have Spring Boot Actuator, comment this checks block out.
[[http_service.checks]]
interval = "10s"
timeout = "2s"
grace_period = "10s"
method = "GET"
path = "/actuator/health"

[[vm]]
memory = "2gb"
cpu_kind = "shared"
cpus = 1
