server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 10000

spring:
  mvc:
    async:
      request-timeout: 30s
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.legakrishi.solar: INFO

management:
  endpoints:
    web:
      exposure:
        include: "health,info"

# src/main/resources/application.yml  (or application-dev.yml if you use profiles)
lkf:
  security:
    partnerStrict: ture
