server:
  port: 8080
  http2:
    enabled: true
  compression:
    enabled: true
    min-response-size: 1024
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json,application/xml
  tomcat:
    threads:
      max: 200
      min-spare: 10
    accept-count: 100
    max-connections: 10000

spring:
  mvc:
    async:
      request-timeout: 30s
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false

logging:
  level:
    root: INFO
    org.springframework.web: INFO
    com.legakrishi.solar: INFO

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - info

lkf:
  monitoring:
    site-id: 1
    device-id: 1
    offline-threshold-minutes: 10
    zero-window-minutes: 5
    zero-min-readings: 3
    zero-threshold-kw: 0.1
    daylight-start: "09:00"
    daylight-end: "17:00"
  security:
    partnerStrict: true

spring:
  jpa:
    hibernate:
      ddl-auto: update   # FIRST launch only; after launch switch to validate
  flyway:
    enabled: false
